name: SinceEighty6
favicon: null
layout_spectrum: 0.8116904452908784
typography_spectrum: 0.7165224519558251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11887018266133964
  lightness: 0.35051279817707837
  saturation: 0.7215755644720048
  rhythmicContrast: 0.055386419873684645
purpose: []
